"""new fields in User field

Revision ID: 148917d3276a
Revises: 967e1d1d0427
Create Date: 2021-04-03 17:26:00.459443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148917d3276a'
down_revision = '967e1d1d0427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
